parameters:
    ibexamailing.default.simple_mailer: ~
    ibexamailing.default.mailing_mailer: ~
    ibexamailing.default.email_subject_prefix: ~
    ibexamailing.default.email_from_address: ~
    ibexamailing.default.email_from_name: ~
    ibexamailing.default.email_return_path: ~
