services:

    nova_ezmailing.ezadminui.component.stylesheets:
        parent: Ibexa\AdminUi\Component\TwigComponent
        public: false
        arguments:
            $template: "@@NovaeZMailing/ezadminui/stylesheets.html.twig"
        tags:
            - { name: ibexa.admin_ui.component, group: 'stylesheet-head' }

    nova_ezmailing.ezadminui.component.javascripts:
        parent: Ibexa\AdminUi\Component\TwigComponent
        public: false
        arguments:
            $template: "@@NovaeZMailing/ezadminui/javascripts.html.twig"
        tags:
            - { name: ibexa.admin_ui.component, group: 'script-body' }
            -
    Novactive\Bundle\eZMailingBundle\Listener\LocationViewGroupTab:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: "ezplatform.tab.group.pre_render", method: "onTabGroupPreRender" }

    Novactive\Bundle\eZMailingBundle\Core\Tab\Campaigns:
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractTab

    Novactive\Bundle\eZMailingBundle\Core\Tab\Mailings:
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractTab
