services:

    ibexamailing.ezadminui.component.stylesheets:
        parent: Ibexa\AdminUi\Component\TwigComponent
        public: false
        arguments:
            $template: "@@IbexaMailing/ezadminui/stylesheets.html.twig"
        tags:
            - { name: ibexa.admin_ui.component, group: 'stylesheet-head' }

    ibexamailing.ezadminui.component.javascripts:
        parent: Ibexa\AdminUi\Component\TwigComponent
        public: false
        arguments:
            $template: "@@IbexaMailing/ezadminui/javascripts.html.twig"
        tags:
            - { name: ibexa.admin_ui.component, group: 'script-body' }

    CodeRhapsodie\IbexaMailingBundle\Listener\LocationViewGroupTab:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: "ezplatform.tab.group.pre_render", method: "onTabGroupPreRender" }

    CodeRhapsodie\IbexaMailingBundle\Core\Tab\Campaigns:
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractTab

    CodeRhapsodie\IbexaMailingBundle\Core\Tab\Mailings:
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractTab
