---
# Monolog configuration
channels: [ 'ibexamailing' ]
handlers:
    ibexamailing:
        # log when email, push or sms are sent
        level: debug
        type: stream
        path: '%kernel.logs_dir%/ibexamailing.log'
        channels: [ 'ibexamailing' ]
    ibexamailingconsole:
            type:   console
            process_psr_3_messages: false
            channels: [ 'ibexamailing' ]
