_ibexamailing_bundle:
    resource: "@IbexaMailingBundle/Controller"
    type:     annotation
    prefix: /ibexamailing

_ibexamailing_ez_content_view:
    path: /ibexamailing/view/{locationId}/{contentId}/{mailingId}
    defaults:
        _controller: ibexa_content:viewAction
        viewType: ibexamailingfull
        layout: true
        mailingId: null
    options:
        expose: true
