system:
    default:
        content_view:
            ibexamailingfull:
                generic:
                    template: "@IbexaMailing/eZViews/ibexamailingfull/generic.html.twig"
                    match:
                        Identifier\ContentType: ['-']
